package org.korolev.automagazine.api.entities;

public enum EventType {
    PAGE_VIEW,
    PRODUCT_VIEW,
    CATEGORY_VIEW,
    SEARCH_RESULTS_VIEW,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    CART_VIEWED,
    CHECKOUT_STARTED,
    CHECKOUT_ABANDONED,
    ORDER_CREATED,
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    LOGIN,
    LOGOUT,
    REGISTRATION,
    SEARCH
}